STOP_WORDS = ["the", "da", "ureport", "u report", "u-report", "yes", "no", "is", "Juba", "ug", "and", "radio",
              "scout", "scouts", "district", "not",
              "are", "their", "they", "from", "heard", "that", "for", "can", "but", "have", "about", "them", "should",
              "Busia",
              "Kiryandongo",
              "Kole",
              "Moroto",
              "Mbarara",
              "Pader",
              "Alebtong",
              "Buvuma",
              "Amuru",
              "Wakiso",
              "Soroti",
              "Rubirizi",
              "Gomba",
              "Butambala",
              "Dokolo",
              "Iganga",
              "Amudat",
              "Ssembabule",
              "Kyenjojo",
              "Kibuku",
              "Luuka",
              "Tororo",
              "Isingiro",
              "Kampala",
              "Apac",
              "Kamuli",
              "Masindi",
              "Bundibugyo",
              "Sheema",
              "Mukono",
              "Nakasongola",
              "Buvuma",
              "Buyende",
              "Hoima",
              "Kanungu",
              "Kisoro",
              "Kamwenge",
              "Katakwi",
              "Kibaale",
              "Kiruhura",
              "Kapchorwa",
              "Kayunga",
              "Kiboga",
              "Koboko",
              "Kotido",
              "Gulu",
              "Kitgum",
              "Namayingo",
              "Nakapiripirit",
              "Kumi",
              "Moyo",
              "Kween",
              "Lamwo",
              "Buliisa",
              "Zombo",
              "Amuria",
              "Amolatar",
              "Agago",
              "Abim",
              "Adjumani",
              "Nwoya",
              "Otuke",
              "Ntungamo",
              "Namutumba",
              "Napak",
              "Mpigi",
              "Oyam",
              "Nakaseke",
              "Bulambuli",
              "Lira",
              "Kaabong",
              "Yumbe",
              "Manafwa",
              "Mitooma",
              "Bushenyi",
              "Kabale",
              "Kabarole",
              "Kalangala",
              "Ntoroko",
              "Mubende",
              "Nebbi",
              "Masaka",
              "Bugiri",
              "Mayuge",
              "Pallisa",
              "Kyankwanzi",
              "Bududa",
              "Buhweju",
              "Mbale",
              "Bukwo",
              "Serere",
              "Rukungiri",
              "Buikwe",
              "Bukedea",
              "Rakai",
              "Bukomansimbi",
              "Budaka",
              "Ibanda",
              "Arua",
              "Jinja",
              "Kaliro",
              "Kaberamaido",
              "Kalungu",
              "Kasese",
              "Butaleja",
              "Mityana",
              "Lyantonde",
              "Kyegegwa",
              "Luwero",
              "Lwengo",
              "Ngora",
              "Maracha",
              "Sironko",
              "should",
              "them",
              "and",
              "their",
              "village",
              "what",
              "from",
              "name",
              "its",
              "our",
              "with",
              "report",
              "some",
              "there",

              "who",

              "because",
              "over",
              "like",
              "also",
              "good",
              "why",

              "you",
              "has",

              "you",
              "years",
              "about",
              "advert",
              "this",
              "iam",
              "through",
              "mps",
              "out",

              "how",
              "more",


              "think",


              "but",

              "will",
              "the",
              "which",


              "other",

              "what",

              "for",

              "are",
              "ureport",

              "know",


              "that",
              "give",
              "district",
              "coz",
              "than",
              "was",
              "what",
              "those",
              "very",
              "when",
              "our", "shd", "all", "such", "your", "through", "know", "know", "every", "may", "bad", "her", "ureporters"
    ,
              "would", "take", "you", "let", "ureport", "due", "against", "can", "the", "how",
              "where", "thank", "don", "not", "sub", "age", "being", "thanks",
              "join", "donyo", "even", "many", "will", "this", "way", "can", "about",
              "was", "with", "the", "use", "had", "any", "only", "have"]
